# Generated by Django 3.2.6 on 2021-10-03 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20211002_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 7, 16, 50, 977368, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
