# Generated by Django 3.2.6 on 2021-10-03 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 7, 16, 55, 20914, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
