# Generated by Django 3.2.6 on 2021-10-17 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 9, 1, 19, 720441, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
