# Generated by Django 3.2.6 on 2021-10-17 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 11, 33, 20, 414021, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
